from django.db import models
from django.utils import timezone


class Trip(models.Model):
    booking_id = models.CharField(max_length=100)
    latitude = models.FloatField()
    longitude = models.FloatField()
    employee_id = models.CharField(max_length=100)
    date = models.DateField()
    in_time = models.TimeField()
    out_time = models.TimeField()
    employee_name = models.CharField(max_length=200)
    gender = models.CharField(max_length=10)
    address = models.TextField()
    city = models.CharField(max_length=100)

class Ride_histories(models.Model):
    booking_id = models.CharField(max_length=100)
    employee_id = models.CharField(max_length=100)
    date = models.DateField(null=True)
    in_time = models.TimeField(null=True)
    out_time = models.TimeField(null=True)
    employee_name = models.CharField(max_length=200)
    gender = models.CharField(max_length=10)
    address = models.TextField()
    city = models.CharField(max_length=100)
    latitude = models.FloatField()
    longitude = models.FloatField()
    VehicleNumber = models.CharField(max_length=100, null=True)
    SeatCapacity = models.IntegerField(null=True)
    vehicle_id = models.IntegerField(null=True)
    CumulativeTravelTime = models.FloatField(null=True)
    add_on = models.DateTimeField(auto_now_add=True)
    priority_order = models.IntegerField(null=True)

class PickUpData(models.Model):
    booking_id = models.CharField(max_length=100,unique=True)
    employee_id = models.CharField(max_length=100)
    date = models.DateField(null=True)
    in_time = models.TimeField(null=True)
    out_time = models.TimeField(null=True)
    employee_name = models.CharField(max_length=200)
    gender = models.CharField(max_length=10)
    address = models.TextField()
    city = models.CharField(max_length=100)
    latitude = models.FloatField()
    longitude = models.FloatField()
    VehicleNumber = models.CharField(max_length=100, null=True)
    SeatCapacity = models.IntegerField(null=True)
    vehicle_id = models.IntegerField(null=True)
    CumulativeTravelTime = models.FloatField(null=True)
    priority_order = models.IntegerField(null=True)
    
#Escorts tables

class VehiclesData(models.Model):    
    VehicleId = models.IntegerField(primary_key=True,null=False) 
    VehicleName = models.CharField(max_length=50,null=True)  
    VehicleNumber = models.CharField(max_length=100)  
    Mileage = models.FloatField(null=True)  
    YearOfManufacturing = models.CharField(max_length=5,null=True) 
    SeatCapacity = models.IntegerField() 
    VehicleType = models.CharField(max_length=50,null=True) 
    VehicleImage = models.CharField(max_length=300,null=True) 
    InsuranceNumber = models.CharField(max_length=100,null=True)  
    FuelType = models.CharField(max_length=30,null=True)  
    VehicleStatus = models.BooleanField(null=True) 
    VendorId = models.CharField(max_length=30,null=True)  
    VendorName = models.CharField(max_length=50,null=True)
    DriverId = models.CharField(max_length=255, null=True, blank=True)
    AddedDate = models.DateField(null=True)

class CabAllocation(models.Model):
    booking_id = models.CharField(max_length=100, unique=True)
    employee_id = models.CharField(max_length=100)
    date = models.DateField(null=True)
    in_time = models.TimeField(null=True)
    out_time = models.TimeField(null=True)
    employee_name = models.CharField(max_length=200)
    gender = models.CharField(max_length=10)
    address = models.TextField()
    city = models.CharField(max_length=100)
    latitude = models.FloatField()
    longitude = models.FloatField()
    VehicleNumber = models.CharField(max_length=100, null=True)
    SeatCapacity = models.IntegerField(null=True)
    vehicle_id = models.IntegerField(null=True)
    CumulativeTravelTime = models.FloatField(null=True)
    priority_order = models.PositiveIntegerField(null=True)

class EscortManagement(models.Model):
    EscortId = models.CharField(max_length=40,unique = True)
    EscortName = models.CharField(max_length=150)
    EscortProfilePicUpload = models.CharField(max_length=300,null = True)
    ContactNumber = models.CharField(max_length=20)
    Age = models.IntegerField()
    AadharCardUpload = models.CharField(max_length=300)
    Address = models.CharField(max_length=300)
    CertificationUpload = models.CharField(max_length=300,null = True)
    AccountHandlerName = models.CharField(max_length=255,null = True)
    AccountNumber = models.CharField(max_length=50,null = True)
    BankName = models.CharField(max_length=100,null = True)
    IFSCCode = models.CharField(max_length=40,null = True)
    BranchName = models.TextField(null = True)
    Shift = models.CharField(max_length = 20,null = True)
    ShiftStartTime = models.TimeField()
    ShiftEndTime = models.TimeField()
    EscortAddedDate = models.DateTimeField(auto_now_add = True)


class DropingData(models.Model):
    booking_id = models.CharField(max_length=100, unique=True)
    employee_id = models.CharField(max_length=100)
    date = models.DateField(null=True)
    in_time = models.TimeField(null=True)
    out_time = models.TimeField(null=True)
    employee_name = models.CharField(max_length=200)
    gender = models.CharField(max_length=10)
    address = models.TextField()
    city = models.CharField(max_length=100)
    latitude = models.FloatField()
    longitude = models.FloatField()
    VehicleNumber = models.CharField(max_length=100, null=True)
    SeatCapacity = models.IntegerField(null=True)
    vehicle_id = models.IntegerField(null=True)
    CumulativeTravelTime = models.FloatField(null=True)
    priority_order = models.PositiveIntegerField(null=True)
    escort_id = models.CharField(max_length=100,null=True)

class Histories(models.Model):
    booking_id = models.CharField(max_length=100)
    employee_id = models.CharField(max_length=100)
    date = models.DateField(null=True)
    in_time = models.TimeField(null=True)
    out_time = models.TimeField(null=True)
    employee_name = models.CharField(max_length=255)
    gender = models.CharField(max_length=10)
    address = models.TextField()
    city = models.CharField(max_length=255)
    latitude = models.FloatField()
    longitude = models.FloatField()
    VehicleNumber = models.CharField(max_length=255, null=True, blank=True)
    SeatCapacity = models.IntegerField(null=True, blank=True)
    vehicle_id = models.IntegerField()
    CumulativeTravelTime = models.FloatField(null=True)
    priority_order = models.IntegerField(null=True, blank=True)
    escort_id = models.CharField(max_length=100,null=True)
    add_on = models.DateTimeField(default=timezone.now)
