# Generated by Django 4.2.5 on 2024-09-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=100, unique=True)),
                ('employee_id', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
                ('in_time', models.TimeField(null=True)),
                ('out_time', models.TimeField(null=True)),
                ('employee_name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('vehicle_number', models.CharField(max_length=100, null=True)),
                ('seat_capacity', models.IntegerField(null=True)),
                ('vehicle_id', models.IntegerField(null=True)),
                ('CumulativeTravelTime', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ride_histories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
                ('in_time', models.TimeField(null=True)),
                ('out_time', models.TimeField(null=True)),
                ('employee_name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('vehicle_number', models.CharField(max_length=100, null=True)),
                ('seat_capacity', models.IntegerField(null=True)),
                ('vehicle_id', models.IntegerField(null=True)),
                ('add_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('employee_id', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('in_time', models.TimeField()),
                ('out_time', models.TimeField()),
                ('employee_name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDetail',
            fields=[
                ('vehicle_number', models.CharField(max_length=100)),
                ('seat_capacity', models.IntegerField()),
                ('vehicleId', models.IntegerField(primary_key=True, serialize=False)),
                ('vehicleName', models.CharField(max_length=255)),
                ('vehicleType', models.CharField(max_length=255)),
                ('vendorName', models.CharField(max_length=255)),
                ('insuranceNumber', models.CharField(max_length=255)),
                ('mileage', models.FloatField()),
                ('yearOfManufacturing', models.IntegerField()),
                ('fuelType', models.CharField(max_length=255)),
                ('vehicleImage', models.URLField()),
                ('driverId', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicleStatus', models.IntegerField()),
            ],
        ),
    ]
