# Generated by Django 4.2.5 on 2024-09-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideallocate', '0004_vehiclesdata_delete_vehicledetail_delete_vehicles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclesdata',
            name='FuelType',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclesdata',
            name='InsuranceNumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclesdata',
            name='Mileage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vehiclesdata',
            name='VehicleName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclesdata',
            name='VehicleStatus',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='vehiclesdata',
            name='VehicleType',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclesdata',
            name='VendorId',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclesdata',
            name='VendorName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclesdata',
            name='YearOfManufacturing',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
