# Generated by Django 4.2.5 on 2024-09-24 07:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rideallocate', '0005_alter_vehiclesdata_fueltype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escortmanagement',
            name='Shift',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='escortmanagement',
            name='AccountHandlerName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='escortmanagement',
            name='AccountNumber',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='escortmanagement',
            name='BankName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='escortmanagement',
            name='BranchName',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='escortmanagement',
            name='CertificationUpload',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='escortmanagement',
            name='EscortAddedDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='escortmanagement',
            name='EscortProfilePicUpload',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='escortmanagement',
            name='IFSCCode',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
