# Generated by Django 4.2.5 on 2024-09-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideallocate', '0006_escortmanagement_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escortmanagement',
            name='BranchName',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='escortmanagement',
            name='EscortId',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='escortmanagement',
            name='EscortName',
            field=models.CharField(max_length=150),
        ),
    ]
