# Generated by Django 4.2.5 on 2024-09-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideallocate', '0007_alter_escortmanagement_branchname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escortmanagement',
            name='EscortAddedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
