# Generated by Django 4.2.5 on 2024-09-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideallocate', '0009_rename_resultescortassign_dropingdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabVacantDetails',
            fields=[
                ('VehicleId', models.IntegerField(primary_key=True, serialize=False)),
                ('VehicleStatus', models.BooleanField(null=True)),
            ],
        ),
    ]
