# Generated by Django 4.2.5 on 2024-09-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideallocate', '0010_cabvacantdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabvacantdetails',
            name='AddedDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cabvacantdetails',
            name='DriverId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cabvacantdetails',
            name='FuelType',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cabvacantdetails',
            name='InsuranceNumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cabvacantdetails',
            name='Mileage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cabvacantdetails',
            name='SeatCapacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cabvacantdetails',
            name='VehicleImage',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='cabvacantdetails',
            name='VehicleName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cabvacantdetails',
            name='VehicleNumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cabvacantdetails',
            name='VehicleType',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cabvacantdetails',
            name='VendorId',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cabvacantdetails',
            name='VendorName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cabvacantdetails',
            name='YearOfManufacturing',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
