# Generated by Django 4.2.5 on 2024-09-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideallocate', '0011_cabvacantdetails_addeddate_cabvacantdetails_driverid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
