# Generated by Django 4.2.5 on 2024-09-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideallocate', '0012_alter_trip_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclesdata',
            name='VehicleShift',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
