# Generated by Django 4.2.5 on 2024-09-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideallocate', '0013_vehiclesdata_vehicleshift'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftVehiclesData',
            fields=[
                ('VehicleId', models.IntegerField(primary_key=True, serialize=False)),
                ('VehicleName', models.CharField(max_length=50, null=True)),
                ('VehicleNumber', models.CharField(max_length=100)),
                ('Mileage', models.FloatField(null=True)),
                ('YearOfManufacturing', models.CharField(max_length=5, null=True)),
                ('SeatCapacity', models.IntegerField()),
                ('VehicleType', models.CharField(max_length=50, null=True)),
                ('VehicleImage', models.CharField(max_length=300, null=True)),
                ('InsuranceNumber', models.CharField(max_length=100, null=True)),
                ('FuelType', models.CharField(max_length=30, null=True)),
                ('VehicleStatus', models.BooleanField(null=True)),
                ('VendorId', models.CharField(max_length=30, null=True)),
                ('VendorName', models.CharField(max_length=50, null=True)),
                ('DriverId', models.CharField(blank=True, max_length=255, null=True)),
                ('AddedDate', models.DateField(null=True)),
                ('VehicleShift', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
